kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-db-pvc
  namespace: bookproject-cicd
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
