name: BookProject CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          python manage.py test


  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Build Docker image
        run: |
          docker build -t petarpetreski24/bookproject-cicd:latest .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push petarpetreski24/bookproject-cicd:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push-docker

  #   steps:
  #     - name: Deploy to production
  #       run: |
  #         echo "Deploying to production"

  notify:
    runs-on: ubuntu-latest
    needs: build-and-push-docker

    steps:
      - name: Notify GitHub on success
        if: success()
        run: |
          curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d '{"body":"Build, test, and Docker build and push to DockerHub succeeded"}' \
              https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments

      - name: Notify GitHub on failure
        if: failure()
        run: |
          curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d '{"body":"Build, test, or Docker build and push to DockerHub failed"}' \
              https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments
